services:
  accounts-service:
    build:
      context: .
      dockerfile: accounts-service/Dockerfile
    container_name: gamepulse-accounts-service
    environment:
      ACCOUNTS_SERVICE_GRPC_ADDR: :9090
    ports:
      - "9090:9090"

  accounts-gateway:
    build:
      context: .
      dockerfile: accounts-gateway/Dockerfile
    container_name: gamepulse-accounts-gateway
    depends_on:
      - accounts-service
    environment:
      ACCOUNTS_GATEWAY_HTTP_ADDR: :8080
      ACCOUNTS_GATEWAY_ACCOUNT_GRPC_ADDR: accounts-service:9090
      ACCOUNTS_GATEWAY_REQUEST_TIMEOUT: 3s
    ports:
      - "8081:8080"

  accounts-web:
    build:
      context: .
      dockerfile: accounts-web/Dockerfile
    container_name: gamepulse-accounts-web
    depends_on:
      - accounts-gateway
    environment:
      ACCOUNTS_WEB_HTTP_ADDR: :8080
      ACCOUNTS_WEB_ACCOUNTS_GATEWAY_GRAPHQL_URL: http://accounts-gateway:8080/query
      ACCOUNTS_WEB_REQUEST_TIMEOUT: 3s
    ports:
      - "8080:8080"
