package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/solardome/gamepulse-platform/accounts-gateway/graph/generated"
	"github.com/solardome/gamepulse-platform/accounts-gateway/graph/model"
)

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (*model.PingResult, error) {
	resp, err := r.AccountClient.Ping(ctx, "accounts-gateway.graphql")
	if err != nil {
		return nil, fmt.Errorf("call accounts-service ping: %w", err)
	}

	return &model.PingResult{
		Message: resp.GetMessage(),
		Service: resp.GetService(),
	}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
